apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: prod
data:
  db_host: "mysql-service.production.svc.cluster.local"
  db_port: "3306"
  db_name: "orderdb"
  log_level: "INFO"
  redis_host: "redis-service"
  app.properties: |
    server.port=8080
    spring.datasource.url=jdbc:mysql://mysql-service:3306/orderdb