apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migration
        image: busybox
        command: ["sh", "-c",
          "echo Running migration... && sleep 5 && echo Migration complete!"]
