apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-v2.1
spec:
  completions: 1 # run once
  backoffLimit: 3 # retry 3 times if fails
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: order-service:v2.1
          command: ["python", "manage.py", "migrate"]
          env:
            - name: DB_HOST
              value: "mysql-service"