apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce # one pod can read-write at a time
  storageClassName: gp3 # use EBS gp3 (defined in StorageClass)
  resources:
    requests:
      storage: 20Gi
